/* -------- */
/* ROTATE.H */
/* -------- */


#define ID_FRAMERC 1

#define ID_START_STOP 10

#define ID_OPTIONS_SUBMENU 11

#define ID_COLORS_SUBMENU 111
#define ID_CSET0 1111
#define ID_CSET1 1112
#define ID_CSET2 1113
#define ID_CSET3 1114
#define ID_CSET4 1115
#define ID_CSET5 1116

#define ID_DELAY_SUBMENU 20
#define ID_DELAY0000 20000
#define ID_DELAY0100 20100
#define ID_DELAY0250 20250
#define ID_DELAY0500 20500
#define ID_DELAY1000 21000
#define ID_EXIT 12
#define TID_ROTATE 1



